apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-chroot"
spec:
  kprobes:
  # __x64_sys_chroot(const char *path)
  - call: "__x64_sys_chroot"
    syscall: true
    args:
      - index: 0
        type: "string"
