name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'

      - name: Install Dependecies
        run: sudo apt install -y gcc nasm make
        
      - name: Install Nim
        run: curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -yes

      - name: Build
        run: make && make_nim

      - name: Smoketest
        run: bash -c "echo y | ./bin/injector ./bin/shellcode.bin ./bin/basic AAAA | grep "from_injector""
